{% set version = "0.7.0" %}

package:
  name: yaml-cpp-split
  version: {{ version }}

source:
  url: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-{{ version }}.tar.gz
  sha256: 43e6a9fcb146ad871515f0d0873947e5d497a1c9c60c58cb102a97b47208b7c3
  patches:
    - pr_1064.patch
    - fix_empty_cmake_variable.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

outputs:
  - name: yaml-cpp
    script: build-dyn.sh   # [unix]
    script: build-dyn.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('yaml-cpp', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
    test:
      files:
        - test/
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      commands:
        - test -f $PREFIX/lib/libyaml-cpp.so  # [not win]
        - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1  # [win]
  - name: yaml-cpp-static
    script: build-static.sh
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
    test:
      commands:
        - test -f $PREFIX/lib/libyaml-cpp.a  # [not win]

about:
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
  doc_url: https://github.com/jbeder/yaml-cpp/wiki/Tutorial
  dev_url: https://github.com/jbeder/yaml-cpp

extra:
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - tadeu
    - seanyen
    - wolfv
